version: 0.0
os: linux
files:
  - source: /backend.jar
    destination: /home/ec2-user/app/
  - source: /stop.sh
    destination: /home/ec2-user/app/scripts/
  - source: /start.sh
    destination: /home/ec2-user/app/scripts/

permissions:
  - object: /home/ec2-user/app/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
  - object: /home/ec2-user/app/scripts/
    pattern: "*.sh"
    mode: 755 # 실행 권한 부여

hooks:
  BeforeInstall:
    - location: stop.sh # discard-paths: yes 로 인해 루트에 있음
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: start.sh
      timeout: 60
      runas: ec2-user