version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/bms
    overwrite: true

permissions:
  - object: /home/ec2-user/bms
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
#  ApplicationStop:
#    - location: stop.sh
#      timeout: 60
#      runas: ec2-user

  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user