version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/bms

permissions:
  - object: /home/ec2-user/bms
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStop:
    - location: deploy-scripts/stop.sh  # 폴더 경로 추가 (중요)
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: deploy-scripts/start.sh # 폴더 경로 추가 (중요)
      timeout: 60
      runas: ec2-user