version: 0.0
os: linux

files:
  - source: backend.jar
    destination: /home/ec2-user/app/
  - source: stop.sh
    destination: /home/ec2-user/app/
  - source: start.sh
    destination: /home/ec2-user/app/

permissions:
  # 1. jar 파일 권한 설정 (개별 지정 혹은 패턴 이용)
  - object: /home/ec2-user/app/
    pattern: "*.jar"
    owner: ec2-user
    group: ec2-user
    mode: 644

  # 2. 스크립트 파일 권한 설정 (실행 권한 755)
  - object: /home/ec2-user/app/
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: health_check.sh
      timeout: 120
      runas: ec2-user