version: 0.0
os: linux

files:
  - source: backend.jar
    destination: /home/ec2-user/app/
  - source: stop.sh
    destination: /home/ec2-user/app/
  - source: start.sh
    destination: /home/ec2-user/app/

permissions:
  - object: /home/ec2-user/app/
    pattern: "**" # 모든 파일에 대해 권한 설정
    owner: ec2-user
    group: ec2-user
    # JAR 파일은 읽기/실행 가능해야 하고, .sh는 755여야 함
  - object: /home/ec2-user/app/
    pattern: "*.sh"
    mode: 755

hooks:
  # 1. 설치 전 기존 서버 종료
  ApplicationStop: # BeforeInstall 보다 ApplicationStop이 더 안전합니다.
    - location: stop.sh
      timeout: 60
      runas: ec2-user

  # 2. 파일이 다 복사된 후 실행
  ApplicationStart: # AfterInstall 보다는 ApplicationStart에서 실행하는 것이 정석입니다.
    - location: start.sh
      timeout: 60
      runas: ec2-user

  # 3. (선택/강추) 서버가 진짜 떴는지 확인
   ValidateService:
     - location: health_check.sh
       timeout: 120
       runas: ec2-user