version: 0.0
os: linux

files:
  - source: backend.jar
    destination: /home/ec2-user/app/
  - source: stop.sh
    destination: /home/ec2-user/app/
  - source: start.sh
    destination: /home/ec2-user/app/

permissions:
  # 1. 디렉토리 및 모든 파일의 기본 소유권 설정 (가장 중요)
  - object: /home/ec2-user/app/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

  # 2. 특정 파일 형식에 대한 추가 권한 (위 설정과 겹치지 않게 mode만 지정)
  - object: /home/ec2-user/app/
    pattern: "*.sh"
    mode: 755

  - object: /home/ec2-user/app/
    pattern: "*.jar"
    mode: 644

hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: health_check.sh
      timeout: 120
      runas: ec2-user