version: 0.0
os: linux

files:
  - source: backend.jar
    destination: /home/ec2-user/app/
  - source: stop.sh
    destination: /home/ec2-user/app/
  - source: start.sh
    destination: /home/ec2-user/app/

permissions:
  - object: /home/ec2-user/app/
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: stop.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: start.sh
      timeout: 60
      runas: ec2-user
