version: 0.2

env:
  variables:
    JAVA_HOME: /usr/lib/jvm/java-17-amazon-corretto

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Java version 확인"
      - java -version
      - mvn -version

  pre_build:
    commands:
      - echo "백엔드 빌드 시작"
      - mvn clean

  build:
    commands:
      - mvn package -DskipTests

  post_build:
    commands:
      - echo "빌드 완료"

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
