version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - chmod +x ./gradlew
      - chmod +x ./deploy-scripts/**
      - java -version
      - ./gradlew --version

  pre_build:
    commands:
      - echo "Gradle 빌드 시작"

  build:
    commands:
      - ./gradlew clean build -x test

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - deploy-scripts/**/*
