version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - java -version
      - ./gradlew --version

  pre_build:
    commands:
      - echo "백엔드 Gradle 빌드 시작"
      - chmod +x gradlew

  build:
    commands:
      - ./gradlew clean build -x test

  post_build:
    commands:
      - echo "빌드 완료"

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes
